export const SET_QUIZ_QUESTIONS_SUCCESS = "SET_QUIZ_QUESTIONS_SUCCESS";
export const SET_QUIZ_QUESTIONS_ERROR = "SET_QUIZ_QUESTIONS_ERROR";
export const GET_QUIZ_QUESTIONS_REQUEST = "GET_QUIZ_QUESTIONS_REQUEST";